module.exports.SMFI_VERSION = 0x01000002;

module.exports.STATUS_CODES = {
	SMFIS_CONTINUE: 0,
	SMFIS_REJECT: 1,
	SMFIS_DISCARD: 2,
	SMFIS_ACCEPT: 3,
	SMFIS_TEMPFAIL: 4,
	SMFIS_NOREPLY: 7,
	SMFIS_SKIP: 8,
	SMFIS_ALL_OPTS: 10
};
